/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SalesReportRouteImport } from './routes/sales-report'
import { Route as PurchaseReportRouteImport } from './routes/purchase-report'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EstimateRouteImport } from './routes/estimate'
import { Route as BuyersRouteImport } from './routes/buyers'
import { Route as BillsRouteImport } from './routes/bills'
import { Route as IndexRouteImport } from './routes/index'

const SalesReportRoute = SalesReportRouteImport.update({
  id: '/sales-report',
  path: '/sales-report',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseReportRoute = PurchaseReportRouteImport.update({
  id: '/purchase-report',
  path: '/purchase-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimateRoute = EstimateRouteImport.update({
  id: '/estimate',
  path: '/estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyersRoute = BuyersRouteImport.update({
  id: '/buyers',
  path: '/buyers',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/buyers': typeof BuyersRoute
  '/estimate': typeof EstimateRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/purchase-report': typeof PurchaseReportRoute
  '/sales-report': typeof SalesReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/buyers': typeof BuyersRoute
  '/estimate': typeof EstimateRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/purchase-report': typeof PurchaseReportRoute
  '/sales-report': typeof SalesReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/buyers': typeof BuyersRoute
  '/estimate': typeof EstimateRoute
  '/login': typeof LoginRoute
  '/products': typeof ProductsRoute
  '/purchase-report': typeof PurchaseReportRoute
  '/sales-report': typeof SalesReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bills'
    | '/buyers'
    | '/estimate'
    | '/login'
    | '/products'
    | '/purchase-report'
    | '/sales-report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bills'
    | '/buyers'
    | '/estimate'
    | '/login'
    | '/products'
    | '/purchase-report'
    | '/sales-report'
  id:
    | '__root__'
    | '/'
    | '/bills'
    | '/buyers'
    | '/estimate'
    | '/login'
    | '/products'
    | '/purchase-report'
    | '/sales-report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillsRoute: typeof BillsRoute
  BuyersRoute: typeof BuyersRoute
  EstimateRoute: typeof EstimateRoute
  LoginRoute: typeof LoginRoute
  ProductsRoute: typeof ProductsRoute
  PurchaseReportRoute: typeof PurchaseReportRoute
  SalesReportRoute: typeof SalesReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sales-report': {
      id: '/sales-report'
      path: '/sales-report'
      fullPath: '/sales-report'
      preLoaderRoute: typeof SalesReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-report': {
      id: '/purchase-report'
      path: '/purchase-report'
      fullPath: '/purchase-report'
      preLoaderRoute: typeof PurchaseReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimate': {
      id: '/estimate'
      path: '/estimate'
      fullPath: '/estimate'
      preLoaderRoute: typeof EstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyers': {
      id: '/buyers'
      path: '/buyers'
      fullPath: '/buyers'
      preLoaderRoute: typeof BuyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills': {
      id: '/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillsRoute: BillsRoute,
  BuyersRoute: BuyersRoute,
  EstimateRoute: EstimateRoute,
  LoginRoute: LoginRoute,
  ProductsRoute: ProductsRoute,
  PurchaseReportRoute: PurchaseReportRoute,
  SalesReportRoute: SalesReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
