/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SalesReportRouteImport } from './routes/sales-report'
import { Route as PurchaseReportRouteImport } from './routes/purchase-report'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EstimateRouteImport } from './routes/estimate'
import { Route as BuyersRouteImport } from './routes/buyers'
import { Route as BillsRouteImport } from './routes/bills'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditIndexRouteImport } from './routes/audit.index'
import { Route as AuditingNewAuditRouteImport } from './routes/auditing.new-audit'
import { Route as AuditVerificationRouteImport } from './routes/audit.verification'
import { Route as AuditSettingsRouteImport } from './routes/audit.settings'
import { Route as AuditReportsRouteImport } from './routes/audit.reports'
import { Route as AuditReconciliationRouteImport } from './routes/audit.reconciliation'
import { Route as AuditInventoryRouteImport } from './routes/audit.inventory'
import { Route as AuditInProgressRouteImport } from './routes/audit.in-progress'
import { Route as AuditHistoryRouteImport } from './routes/audit.history'
import { Route as AuditingNewAuditVerifyRouteImport } from './routes/auditing.new-audit.verify'
import { Route as AuditingNewAuditReviewRouteImport } from './routes/auditing.new-audit.review'

const SalesReportRoute = SalesReportRouteImport.update({
  id: '/sales-report',
  path: '/sales-report',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseReportRoute = PurchaseReportRouteImport.update({
  id: '/purchase-report',
  path: '/purchase-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimateRoute = EstimateRouteImport.update({
  id: '/estimate',
  path: '/estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyersRoute = BuyersRouteImport.update({
  id: '/buyers',
  path: '/buyers',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditIndexRoute = AuditIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuditRoute,
} as any)
const AuditingNewAuditRoute = AuditingNewAuditRouteImport.update({
  id: '/auditing/new-audit',
  path: '/auditing/new-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditVerificationRoute = AuditVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AuditRoute,
} as any)
const AuditSettingsRoute = AuditSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuditRoute,
} as any)
const AuditReportsRoute = AuditReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuditRoute,
} as any)
const AuditReconciliationRoute = AuditReconciliationRouteImport.update({
  id: '/reconciliation',
  path: '/reconciliation',
  getParentRoute: () => AuditRoute,
} as any)
const AuditInventoryRoute = AuditInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuditRoute,
} as any)
const AuditInProgressRoute = AuditInProgressRouteImport.update({
  id: '/in-progress',
  path: '/in-progress',
  getParentRoute: () => AuditRoute,
} as any)
const AuditHistoryRoute = AuditHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuditRoute,
} as any)
const AuditingNewAuditVerifyRoute = AuditingNewAuditVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuditingNewAuditRoute,
} as any)
const AuditingNewAuditReviewRoute = AuditingNewAuditReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuditingNewAuditRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRouteWithChildren
  '/bills': typeof BillsRoute
  '/buyers': typeof BuyersRoute
  '/estimate': typeof EstimateRoute
  '/login': typeof LoginRoute
  '/modules': typeof ModulesRoute
  '/products': typeof ProductsRoute
  '/purchase-report': typeof PurchaseReportRoute
  '/sales-report': typeof SalesReportRoute
  '/audit/history': typeof AuditHistoryRoute
  '/audit/in-progress': typeof AuditInProgressRoute
  '/audit/inventory': typeof AuditInventoryRoute
  '/audit/reconciliation': typeof AuditReconciliationRoute
  '/audit/reports': typeof AuditReportsRoute
  '/audit/settings': typeof AuditSettingsRoute
  '/audit/verification': typeof AuditVerificationRoute
  '/auditing/new-audit': typeof AuditingNewAuditRouteWithChildren
  '/audit/': typeof AuditIndexRoute
  '/auditing/new-audit/review': typeof AuditingNewAuditReviewRoute
  '/auditing/new-audit/verify': typeof AuditingNewAuditVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/buyers': typeof BuyersRoute
  '/estimate': typeof EstimateRoute
  '/login': typeof LoginRoute
  '/modules': typeof ModulesRoute
  '/products': typeof ProductsRoute
  '/purchase-report': typeof PurchaseReportRoute
  '/sales-report': typeof SalesReportRoute
  '/audit/history': typeof AuditHistoryRoute
  '/audit/in-progress': typeof AuditInProgressRoute
  '/audit/inventory': typeof AuditInventoryRoute
  '/audit/reconciliation': typeof AuditReconciliationRoute
  '/audit/reports': typeof AuditReportsRoute
  '/audit/settings': typeof AuditSettingsRoute
  '/audit/verification': typeof AuditVerificationRoute
  '/auditing/new-audit': typeof AuditingNewAuditRouteWithChildren
  '/audit': typeof AuditIndexRoute
  '/auditing/new-audit/review': typeof AuditingNewAuditReviewRoute
  '/auditing/new-audit/verify': typeof AuditingNewAuditVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRouteWithChildren
  '/bills': typeof BillsRoute
  '/buyers': typeof BuyersRoute
  '/estimate': typeof EstimateRoute
  '/login': typeof LoginRoute
  '/modules': typeof ModulesRoute
  '/products': typeof ProductsRoute
  '/purchase-report': typeof PurchaseReportRoute
  '/sales-report': typeof SalesReportRoute
  '/audit/history': typeof AuditHistoryRoute
  '/audit/in-progress': typeof AuditInProgressRoute
  '/audit/inventory': typeof AuditInventoryRoute
  '/audit/reconciliation': typeof AuditReconciliationRoute
  '/audit/reports': typeof AuditReportsRoute
  '/audit/settings': typeof AuditSettingsRoute
  '/audit/verification': typeof AuditVerificationRoute
  '/auditing/new-audit': typeof AuditingNewAuditRouteWithChildren
  '/audit/': typeof AuditIndexRoute
  '/auditing/new-audit/review': typeof AuditingNewAuditReviewRoute
  '/auditing/new-audit/verify': typeof AuditingNewAuditVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/bills'
    | '/buyers'
    | '/estimate'
    | '/login'
    | '/modules'
    | '/products'
    | '/purchase-report'
    | '/sales-report'
    | '/audit/history'
    | '/audit/in-progress'
    | '/audit/inventory'
    | '/audit/reconciliation'
    | '/audit/reports'
    | '/audit/settings'
    | '/audit/verification'
    | '/auditing/new-audit'
    | '/audit/'
    | '/auditing/new-audit/review'
    | '/auditing/new-audit/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bills'
    | '/buyers'
    | '/estimate'
    | '/login'
    | '/modules'
    | '/products'
    | '/purchase-report'
    | '/sales-report'
    | '/audit/history'
    | '/audit/in-progress'
    | '/audit/inventory'
    | '/audit/reconciliation'
    | '/audit/reports'
    | '/audit/settings'
    | '/audit/verification'
    | '/auditing/new-audit'
    | '/audit'
    | '/auditing/new-audit/review'
    | '/auditing/new-audit/verify'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/bills'
    | '/buyers'
    | '/estimate'
    | '/login'
    | '/modules'
    | '/products'
    | '/purchase-report'
    | '/sales-report'
    | '/audit/history'
    | '/audit/in-progress'
    | '/audit/inventory'
    | '/audit/reconciliation'
    | '/audit/reports'
    | '/audit/settings'
    | '/audit/verification'
    | '/auditing/new-audit'
    | '/audit/'
    | '/auditing/new-audit/review'
    | '/auditing/new-audit/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRouteWithChildren
  BillsRoute: typeof BillsRoute
  BuyersRoute: typeof BuyersRoute
  EstimateRoute: typeof EstimateRoute
  LoginRoute: typeof LoginRoute
  ModulesRoute: typeof ModulesRoute
  ProductsRoute: typeof ProductsRoute
  PurchaseReportRoute: typeof PurchaseReportRoute
  SalesReportRoute: typeof SalesReportRoute
  AuditingNewAuditRoute: typeof AuditingNewAuditRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sales-report': {
      id: '/sales-report'
      path: '/sales-report'
      fullPath: '/sales-report'
      preLoaderRoute: typeof SalesReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-report': {
      id: '/purchase-report'
      path: '/purchase-report'
      fullPath: '/purchase-report'
      preLoaderRoute: typeof PurchaseReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimate': {
      id: '/estimate'
      path: '/estimate'
      fullPath: '/estimate'
      preLoaderRoute: typeof EstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyers': {
      id: '/buyers'
      path: '/buyers'
      fullPath: '/buyers'
      preLoaderRoute: typeof BuyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills': {
      id: '/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/': {
      id: '/audit/'
      path: '/'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuditIndexRouteImport
      parentRoute: typeof AuditRoute
    }
    '/auditing/new-audit': {
      id: '/auditing/new-audit'
      path: '/auditing/new-audit'
      fullPath: '/auditing/new-audit'
      preLoaderRoute: typeof AuditingNewAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/verification': {
      id: '/audit/verification'
      path: '/verification'
      fullPath: '/audit/verification'
      preLoaderRoute: typeof AuditVerificationRouteImport
      parentRoute: typeof AuditRoute
    }
    '/audit/settings': {
      id: '/audit/settings'
      path: '/settings'
      fullPath: '/audit/settings'
      preLoaderRoute: typeof AuditSettingsRouteImport
      parentRoute: typeof AuditRoute
    }
    '/audit/reports': {
      id: '/audit/reports'
      path: '/reports'
      fullPath: '/audit/reports'
      preLoaderRoute: typeof AuditReportsRouteImport
      parentRoute: typeof AuditRoute
    }
    '/audit/reconciliation': {
      id: '/audit/reconciliation'
      path: '/reconciliation'
      fullPath: '/audit/reconciliation'
      preLoaderRoute: typeof AuditReconciliationRouteImport
      parentRoute: typeof AuditRoute
    }
    '/audit/inventory': {
      id: '/audit/inventory'
      path: '/inventory'
      fullPath: '/audit/inventory'
      preLoaderRoute: typeof AuditInventoryRouteImport
      parentRoute: typeof AuditRoute
    }
    '/audit/in-progress': {
      id: '/audit/in-progress'
      path: '/in-progress'
      fullPath: '/audit/in-progress'
      preLoaderRoute: typeof AuditInProgressRouteImport
      parentRoute: typeof AuditRoute
    }
    '/audit/history': {
      id: '/audit/history'
      path: '/history'
      fullPath: '/audit/history'
      preLoaderRoute: typeof AuditHistoryRouteImport
      parentRoute: typeof AuditRoute
    }
    '/auditing/new-audit/verify': {
      id: '/auditing/new-audit/verify'
      path: '/verify'
      fullPath: '/auditing/new-audit/verify'
      preLoaderRoute: typeof AuditingNewAuditVerifyRouteImport
      parentRoute: typeof AuditingNewAuditRoute
    }
    '/auditing/new-audit/review': {
      id: '/auditing/new-audit/review'
      path: '/review'
      fullPath: '/auditing/new-audit/review'
      preLoaderRoute: typeof AuditingNewAuditReviewRouteImport
      parentRoute: typeof AuditingNewAuditRoute
    }
  }
}

interface AuditRouteChildren {
  AuditHistoryRoute: typeof AuditHistoryRoute
  AuditInProgressRoute: typeof AuditInProgressRoute
  AuditInventoryRoute: typeof AuditInventoryRoute
  AuditReconciliationRoute: typeof AuditReconciliationRoute
  AuditReportsRoute: typeof AuditReportsRoute
  AuditSettingsRoute: typeof AuditSettingsRoute
  AuditVerificationRoute: typeof AuditVerificationRoute
  AuditIndexRoute: typeof AuditIndexRoute
}

const AuditRouteChildren: AuditRouteChildren = {
  AuditHistoryRoute: AuditHistoryRoute,
  AuditInProgressRoute: AuditInProgressRoute,
  AuditInventoryRoute: AuditInventoryRoute,
  AuditReconciliationRoute: AuditReconciliationRoute,
  AuditReportsRoute: AuditReportsRoute,
  AuditSettingsRoute: AuditSettingsRoute,
  AuditVerificationRoute: AuditVerificationRoute,
  AuditIndexRoute: AuditIndexRoute,
}

const AuditRouteWithChildren = AuditRoute._addFileChildren(AuditRouteChildren)

interface AuditingNewAuditRouteChildren {
  AuditingNewAuditReviewRoute: typeof AuditingNewAuditReviewRoute
  AuditingNewAuditVerifyRoute: typeof AuditingNewAuditVerifyRoute
}

const AuditingNewAuditRouteChildren: AuditingNewAuditRouteChildren = {
  AuditingNewAuditReviewRoute: AuditingNewAuditReviewRoute,
  AuditingNewAuditVerifyRoute: AuditingNewAuditVerifyRoute,
}

const AuditingNewAuditRouteWithChildren =
  AuditingNewAuditRoute._addFileChildren(AuditingNewAuditRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRouteWithChildren,
  BillsRoute: BillsRoute,
  BuyersRoute: BuyersRoute,
  EstimateRoute: EstimateRoute,
  LoginRoute: LoginRoute,
  ModulesRoute: ModulesRoute,
  ProductsRoute: ProductsRoute,
  PurchaseReportRoute: PurchaseReportRoute,
  SalesReportRoute: SalesReportRoute,
  AuditingNewAuditRoute: AuditingNewAuditRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
