/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SalesReportRouteImport } from './routes/sales-report'
import { Route as PurchaseReportRouteImport } from './routes/purchase-report'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EstimateRouteImport } from './routes/estimate'
import { Route as BuyersRouteImport } from './routes/buyers'
import { Route as BillsRouteImport } from './routes/bills'
import { Route as AuditingRouteImport } from './routes/auditing'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditingIndexRouteImport } from './routes/auditing.index'
import { Route as AuditingDashboardRouteImport } from './routes/auditing.dashboard'

const SalesReportRoute = SalesReportRouteImport.update({
  id: '/sales-report',
  path: '/sales-report',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseReportRoute = PurchaseReportRouteImport.update({
  id: '/purchase-report',
  path: '/purchase-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimateRoute = EstimateRouteImport.update({
  id: '/estimate',
  path: '/estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyersRoute = BuyersRouteImport.update({
  id: '/buyers',
  path: '/buyers',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditingRoute = AuditingRouteImport.update({
  id: '/auditing',
  path: '/auditing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditingIndexRoute = AuditingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuditingRoute,
} as any)
const AuditingDashboardRoute = AuditingDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuditingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auditing': typeof AuditingRouteWithChildren
  '/bills': typeof BillsRoute
  '/buyers': typeof BuyersRoute
  '/estimate': typeof EstimateRoute
  '/login': typeof LoginRoute
  '/modules': typeof ModulesRoute
  '/products': typeof ProductsRoute
  '/purchase-report': typeof PurchaseReportRoute
  '/sales-report': typeof SalesReportRoute
  '/auditing/dashboard': typeof AuditingDashboardRoute
  '/auditing/': typeof AuditingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/buyers': typeof BuyersRoute
  '/estimate': typeof EstimateRoute
  '/login': typeof LoginRoute
  '/modules': typeof ModulesRoute
  '/products': typeof ProductsRoute
  '/purchase-report': typeof PurchaseReportRoute
  '/sales-report': typeof SalesReportRoute
  '/auditing/dashboard': typeof AuditingDashboardRoute
  '/auditing': typeof AuditingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auditing': typeof AuditingRouteWithChildren
  '/bills': typeof BillsRoute
  '/buyers': typeof BuyersRoute
  '/estimate': typeof EstimateRoute
  '/login': typeof LoginRoute
  '/modules': typeof ModulesRoute
  '/products': typeof ProductsRoute
  '/purchase-report': typeof PurchaseReportRoute
  '/sales-report': typeof SalesReportRoute
  '/auditing/dashboard': typeof AuditingDashboardRoute
  '/auditing/': typeof AuditingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auditing'
    | '/bills'
    | '/buyers'
    | '/estimate'
    | '/login'
    | '/modules'
    | '/products'
    | '/purchase-report'
    | '/sales-report'
    | '/auditing/dashboard'
    | '/auditing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bills'
    | '/buyers'
    | '/estimate'
    | '/login'
    | '/modules'
    | '/products'
    | '/purchase-report'
    | '/sales-report'
    | '/auditing/dashboard'
    | '/auditing'
  id:
    | '__root__'
    | '/'
    | '/auditing'
    | '/bills'
    | '/buyers'
    | '/estimate'
    | '/login'
    | '/modules'
    | '/products'
    | '/purchase-report'
    | '/sales-report'
    | '/auditing/dashboard'
    | '/auditing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditingRoute: typeof AuditingRouteWithChildren
  BillsRoute: typeof BillsRoute
  BuyersRoute: typeof BuyersRoute
  EstimateRoute: typeof EstimateRoute
  LoginRoute: typeof LoginRoute
  ModulesRoute: typeof ModulesRoute
  ProductsRoute: typeof ProductsRoute
  PurchaseReportRoute: typeof PurchaseReportRoute
  SalesReportRoute: typeof SalesReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sales-report': {
      id: '/sales-report'
      path: '/sales-report'
      fullPath: '/sales-report'
      preLoaderRoute: typeof SalesReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-report': {
      id: '/purchase-report'
      path: '/purchase-report'
      fullPath: '/purchase-report'
      preLoaderRoute: typeof PurchaseReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimate': {
      id: '/estimate'
      path: '/estimate'
      fullPath: '/estimate'
      preLoaderRoute: typeof EstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyers': {
      id: '/buyers'
      path: '/buyers'
      fullPath: '/buyers'
      preLoaderRoute: typeof BuyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills': {
      id: '/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditing': {
      id: '/auditing'
      path: '/auditing'
      fullPath: '/auditing'
      preLoaderRoute: typeof AuditingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditing/': {
      id: '/auditing/'
      path: '/'
      fullPath: '/auditing/'
      preLoaderRoute: typeof AuditingIndexRouteImport
      parentRoute: typeof AuditingRoute
    }
    '/auditing/dashboard': {
      id: '/auditing/dashboard'
      path: '/dashboard'
      fullPath: '/auditing/dashboard'
      preLoaderRoute: typeof AuditingDashboardRouteImport
      parentRoute: typeof AuditingRoute
    }
  }
}

interface AuditingRouteChildren {
  AuditingDashboardRoute: typeof AuditingDashboardRoute
  AuditingIndexRoute: typeof AuditingIndexRoute
}

const AuditingRouteChildren: AuditingRouteChildren = {
  AuditingDashboardRoute: AuditingDashboardRoute,
  AuditingIndexRoute: AuditingIndexRoute,
}

const AuditingRouteWithChildren = AuditingRoute._addFileChildren(
  AuditingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditingRoute: AuditingRouteWithChildren,
  BillsRoute: BillsRoute,
  BuyersRoute: BuyersRoute,
  EstimateRoute: EstimateRoute,
  LoginRoute: LoginRoute,
  ModulesRoute: ModulesRoute,
  ProductsRoute: ProductsRoute,
  PurchaseReportRoute: PurchaseReportRoute,
  SalesReportRoute: SalesReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
